apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: nginx:1.14.2
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        resource/test: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        resource/test: 1
    ports:
      - containerPort: 80
